# Generated by Django 4.2.3 on 2023-08-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('three', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
